# -*- coding: utf-8 -*-
"""102303726_Mashup.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1knnoKHAxrch8ViWB1lhlt8_5DVZEgDGM
"""

!pip install yt-dlp pydub -q


!apt-get update -qq
!apt-get install -y ffmpeg -qq

print("All dependencies installed!")

# Commented out IPython magic to ensure Python compatibility.
# %%writefile 102303726.py
# import sys
# import os
# from yt_dlp import YoutubeDL
# from pydub import AudioSegment
# import subprocess
# 
# def main():
#     # Check correct number of parameters
#     if len(sys.argv) != 5:
#         print(" Error: Incorrect number of parameters.")
#         print("Usage: python 102303726.py \"Singer Name\" N Y output.mp3")
#         print("Example: python 102303726.py \"Sharry Maan\" 20 20 102303726-output.mp3")
#         sys.exit(1)
# 
#     singer = sys.argv[1]
# 
#     # Validate N and Y as integers
#     try:
#         N = int(sys.argv[2])
#         Y = int(sys.argv[3])
#     except ValueError:
#         print(" Error: N and Y must be positive integers.")
#         sys.exit(1)
# 
#     output_file = sys.argv[4]
# 
#     # Validate N > 10 and Y > 20
#     if N <= 10 or Y <= 20:
#         print(" Error: N must be greater than 10 and Y must be greater than 20.")
#         sys.exit(1)
# 
#     print(f" Starting Mashup for '{singer}' | N={N} videos | Y={Y} sec | Output: {output_file}")
# 
#     try:
#         # Step 1: Search and get video URLs
#         print(" Searching YouTube for videos...")
#         search_opts = {
#             'quiet': True,
#             'extract_flat': True,
#             'skip_download': True,
#         }
#         with YoutubeDL(search_opts) as ydl:
#             search_info = ydl.extract_info(f'ytsearch{N}:{singer}', download=False)
#             entries = search_info.get('entries', [])
# 
#         video_urls = [entry['url'] for entry in entries if entry and 'url' in entry][:N]
# 
#         if not video_urls:
#             print(" Error: No videos found for this singer.")
#             sys.exit(1)
# 
#         # Step 2: Download N videos as MP4
#         print(" Downloading videos...")
#         downloaded_files = []
#         download_opts = {
#             'format': 'bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best',
#             'outtmpl': '%(id)s.%(ext)s',
#             'quiet': False,
#             'no_warnings': True,
#             'ignoreerrors': True,
#         }
# 
#         for i, url in enumerate(video_urls):
#             print(f"   Downloading video {i+1}/{N}...")
#             try:
#                 with YoutubeDL(download_opts) as ydl:
#                     info_dict = ydl.extract_info(url, download=True)
#                     filename = ydl.prepare_filename(info_dict)
#                     # Handle possible extensions
#                     for ext in ['mp4', 'mkv', 'webm']:
#                         alt_file = filename.rsplit('.', 1)[0] + '.' + ext
#                         if os.path.exists(alt_file):
#                             filename = alt_file
#                             break
#                     if os.path.exists(filename):
#                         downloaded_files.append(filename)
#             except Exception as e:
#                 print(f"    Skipped video {i+1}: {str(e)[:100]}")
#                 continue
# 
#         if len(downloaded_files) < N // 2:
#             print(" Warning: Fewer videos downloaded than expected.")
# 
#         # Step 3: Convert videos to audio (MP3)
#         print(" Converting to audio...")
#         audio_files = []
#         for vid_file in downloaded_files:
#             try:
#                 audio_file = vid_file.rsplit('.', 1)[0] + '.mp3'
#                 cmd = [
#                     'ffmpeg', '-i', vid_file, '-vn', '-acodec', 'libmp3lame',
#                     '-qscale:a', '2', audio_file, '-y'
#                 ]
#                 subprocess.run(cmd, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL, check=True)
#                 if os.path.exists(audio_file):
#                     audio_files.append(audio_file)
#             except:
#                 print(f"    Failed to convert {vid_file}")
#                 continue
# 
#         # Step 4: Cut first Y seconds
#         print(" Cutting first Y seconds...")
#         cut_files = []
#         for aud_file in audio_files:
#             try:
#                 audio = AudioSegment.from_file(aud_file, format="mp3")
#                 cut_audio = audio[:Y * 1000]  # Convert seconds to milliseconds
#                 cut_file = aud_file.rsplit('.', 1)[0] + '_cut.mp3'
#                 cut_audio.export(cut_file, format="mp3")
#                 cut_files.append(cut_file)
#             except Exception as e:
#                 print(f"    Error cutting {aud_file}: {str(e)[:100]}")
#                 continue
# 
#         if not cut_files:
#             print(" Error: No audio clips to merge.")
#             sys.exit(1)
# 
#         # Step 5: Merge all cut audios
#         print(" Merging into single output...")
#         combined = AudioSegment.from_file(cut_files[0], format="mp3")
#         for cf in cut_files[1:]:
#             combined += AudioSegment.from_file(cf, format="mp3")
# 
#         combined.export(output_file, format="mp3")
#         print(f" SUCCESS! Mashup saved as: {output_file}")
# 
#     except Exception as e:
#         print(f" Unexpected error: {str(e)}")
#         sys.exit(1)
#     finally:
#         # Cleanup temporary files
#         print(" Cleaning up...")
#         all_temp = downloaded_files + audio_files + cut_files
#         for f in all_temp:
#             if os.path.exists(f):
#                 try:
#                     os.remove(f)
#                 except:
#                     pass
# 
# if __name__ == "__main__":
#     main()

!python 102303726.py "Sharry Maan" 12 25 102303726-output.mp3

